services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: shooting-frontend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: shooting-backend
    restart: unless-stopped
    volumes:
      - ./backend_data:/app/uploads
      - ./backend_data/journal.db:/app/journal.db
    environment:
      - PORT=8000
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: shooting-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend_data:/app/uploads:ro 
    depends_on:
      - backend
      - frontend